### ISSUE TITLE
Not working as viewstate in data of qr.stringfy is not defind

### ISSUE THREAD

**Issue by civdix** [Dydipanshu/AKTU-DOB-FINDER#1]
Trying date: 14/4/2003
Error in execution: ReferenceError: viewstate is not defined
    at find (C:\Users\Acer\AKTU-DOB-FINDER\index.js:39:18)
    at processRollNumber (C:\Users\Acer\AKTU-DOB-FINDER\index.js:175:32)
    at main (C:\Users\Acer\AKTU-DOB-FINDER\index.js:205:26)
    at Object.<anonymous> (C:\Users\Acer\AKTU-DOB-FINDER\index.js:216:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49
Trying date: 15/4/2003
Error in execution: ReferenceError: viewstate is not defined
    at find (C:\Users\Acer\AKTU-DOB-FINDER\index.js:39:18)
    at processRollNumber (C:\Users\Acer\AKTU-DOB-FINDER\index.js:175:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\Users\Acer\AKTU-DOB-FINDER\index.js:205:20)
Trying date: 16/4/2003
Error in execution: ReferenceError: viewstate is not defined
    at find (C:\Users\Acer\AKTU-DOB-FINDER\index.js:39:18)
    at processRollNumber (C:\Users\Acer\AKTU-DOB-FINDER\index.js:175:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\Users\Acer\AKTU-DOB-FINDER\index.js:205:20)

**Comment by Dydipanshu** [comment]
This is intentional. You can get three values __VIEWSTATE,__VIEWSTATEGENERATOR,__EVENTVALIDATION from the AKTU POST request in the network tab 
![AKTU post request](https://github.com/user-attachments/assets/119636f5-2291-478e-8477-2f8add37fe89)

**Comment by Dydipanshu** [comment]
@civdix Now it will work as expected
